default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Sakthik7@
# socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: urlshortner_production

  production:
  adapter: postgresql
  encoding: unicode
  database: urlshortner_production
  username: postgres
  password: Sakthik7@
  host: localhost
  port: 5432